### ISSUE TITLE
Object Lock Error Responses Wrong/Weird

### ISSUE THREAD

**Issue by ferristocrat** [storj/edge#498]
The following object lock related actions returned an "unauthorized" error rather than the appropriate error.

| Action | Example Request | Response | Expected response |
|:---:|:---:|:---:|---|
| PutBucketVersioning | ```aws s3api put-bucket-versioning --bucket my-bucket --versioning-configuration Status=Suspended --endpoint-url https://gateway.qa.storjshare.io``` | An error occurred (AccessDenied) when calling the PutBucketVersioning operation: Access Denied. | Not sure, but probably something different than the current response. |
| DeleteObject (with retention set) | aws s3api delete-object --bucket my-bucket --key my-object --version-id 0000000000000001a008c98f1d6afe18 --endpoint-url https://gateway.qa.storjshare.io | An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied | Not sure, but probably something different than the current response. |
| PutObjectLegalHold | aws s3api put-object-legal-hold --bucket my-bucket --key my-object --legal-hold '{ \"Status\": \"ON\"}' --endpoint-url https://gateway.qa.storjshare.io | An error occurred (InvalidRequest) when calling the PutObjectLegalHold operation: Bucket is missing ObjectLockConfiguration | Would expect "not implemented" response |

See columns G, H, I for more context: https://docs.google.com/spreadsheets/d/1Yfz1sSTRD2nTRAkgGJ27aAv7wTMJCd-74fJlujdNPBw/edit?gid=0#gid=0

**Comment by halkyon** [comment]
Additional unmapped or incorrect errors discovered in tests: https://review.dev.storj.io/c/storj/edge/+/14432

* `GetObjectRetention` on an object without retention unmapped error: `object retention not found: object does not have a retention configuration`. Maybe this should be `InvalidRequest`.
* `PutObject` (and possibly `PutObjectRetention`) with governance mode unmapped error: `invalid retention mode 0, expected 1 (compliance)`
* `PutObjectRetention` on an object with a retain until date in the past produced `MalformedXML` error instead of `InvalidRequest`.
* `PutObject` when attempting to set lock settings on unversioned bucket produces unmapped error `cannot specify Object Lock settings when uploading into a bucket without Versioning enabled`

`AccessDenied` instead of `InvalidRequest` on attempting to delete a locked object version is down to minio doing it's own validation, but it doesn't know if a bucket is locked or not. Setting `STORJ_MINIO_LOCK_ENABLED=1` on the gateway makes it work correctly, but we should move this validation into the object layer instead. There is a similar issue with `CopyObject` here: https://github.com/storj/edge/issues/499

**Comment by halkyon** [comment]
Jeremy mentioned that S3 returns `AccessDenied` if attempting to delete a locked object, so that one should probably stay as it is.

**Comment by halkyon** [comment]
S3 error response research:

* GetObjectLockConfiguration on bucket without object lock:

HTTP 404:
ObjectLockConfigurationNotFoundError: Object Lock configuration does not exist for this bucket

* PutObjectLockConfiguration on bucket without versioning enabled:

HTTP 409:
InvalidBucketState: Versioning must be 'Enabled' on the bucket to apply a Object Lock configuration

* PutObject with retain date in the past:

HTTP 400:
InvalidArgument: The retain until date must be in the future!

* PutObject with correct retention settings, versioning not enabled on bucket and no bucket lock configuration:

HTTP 400:
InvalidRequest: Bucket is missing ObjectLockConfiguration

* PutObject with correct retention settings, versioning is enabled on bucket and no bucket lock configuration:

HTTP 400:
InvalidRequest: Bucket is missing ObjectLockConfiguration

* DeleteObject locked version:

HTTP 403:
An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied because object protected by object lock.

* Try to suspend versioning on bucket with object lock configuration:

HTTP 409:
InvalidBucketState: An Object Lock configuration is present on this bucket, so the versioning state cannot be changed
